# Generated by Django 4.2.7 on 2024-10-21 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='identification_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='identification_type',
        ),
    ]
