# Generated by Django 4.2.7 on 2024-09-23 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaterals',
            name='valuation_report',
            field=models.FileField(blank=True, help_text='Upload the valuation report document.', null=True, upload_to='valuation_reports/'),
        ),
        migrations.AddField(
            model_name='customerdocuments',
            name='documentfile',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='borrower_signature',
            field=models.FileField(default=1, upload_to='signatures/borrowers/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='lender_signature',
            field=models.FileField(default=1, upload_to='signatures/lenders/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collaterals',
            name='collateral_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.collateraltype'),
        ),
        migrations.AlterField(
            model_name='collaterals',
            name='collateral_value',
            field=models.DecimalField(decimal_places=2, help_text='Monetary value of the collateral', max_digits=12),
        ),
        migrations.AlterField(
            model_name='collaterals',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.company'),
        ),
        migrations.AlterField(
            model_name='collaterals',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer'),
        ),
        migrations.AlterField(
            model_name='collaterals',
            name='loanapp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.loanapplication'),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.company'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_income',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='identification_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.identificationtype'),
        ),
        migrations.AlterField(
            model_name='customerdocuments',
            name='uploaded_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer'),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.currency'),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='disbursement_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='disbursementmethod',
            name='amount_disbursed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='disbursementmethod',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.bankaccount'),
        ),
        migrations.AlterField(
            model_name='disbursementmethod',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.currency'),
        ),
        migrations.AlterField(
            model_name='disbursementmethod',
            name='disbursement_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='disbursementmethod',
            name='disbursement_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_disbursement', to='mainapp.disbursement'),
        ),
        migrations.AlterField(
            model_name='identificationtype',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.company'),
        ),
        migrations.AlterField(
            model_name='loanagreement',
            name='agreement_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loanagreement',
            name='loanapp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_loan_id', to='mainapp.loanapplication'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='application_status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='applied_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='interest_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='tenure',
            field=models.IntegerField(help_text='Duration of the loan in months'),
        ),
        migrations.AlterField(
            model_name='loancalculators',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='loancalculators',
            name='interest_basics',
            field=models.CharField(choices=[('365', '365 Days Basis'), ('other', 'Other Basis')], max_length=100),
        ),
        migrations.AlterField(
            model_name='loancalculators',
            name='loan_calculation_method',
            field=models.CharField(choices=[('reducing_balance', 'Reducing Balance Method'), ('flat_rate', 'Flat Rate Method'), ('constant_repayment', 'Constant Repayment (Amortization)'), ('simple_interest', 'Simple Interest'), ('compound_interest', 'Compound Interest'), ('graduated_repayment', 'Graduated Repayment'), ('balloon_payment', 'Balloon Payment'), ('bullet_repayment', 'Bullet Repayment'), ('interest_first', 'Interest-Only Loans')], max_length=150),
        ),
        migrations.AlterField(
            model_name='loancalculators',
            name='repayment_mode',
            field=models.CharField(choices=[('principal_only', 'Principal Only'), ('interest_only', 'Interest Only'), ('both', 'Principal and Interest'), ('interest_first', 'Interest First, Principal Later'), ('principal_end', 'Principal at End, Interest Periodically')], max_length=100),
        ),
        migrations.AlterField(
            model_name='loancalculators',
            name='repayment_schedule',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('halfyearly', 'Half Yearly'), ('annually', 'Annually'), ('one_time', 'One Time')], max_length=100),
        ),
        migrations.AlterField(
            model_name='loancalculators',
            name='tenure',
            field=models.IntegerField(help_text='Tenure in days/weeks/months/years depending on the schedule.'),
        ),
        migrations.AlterField(
            model_name='loancalculators',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='loanclosure',
            name='closure_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='loanclosure',
            name='closure_method',
            field=models.CharField(choices=[('lump sum Payment', 'lump sum Payment'), ('Refinancing', 'Refinancing')], max_length=50),
        ),
        migrations.AlterField(
            model_name='loanclosure',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.company'),
        ),
        migrations.AlterField(
            model_name='loanclosure',
            name='loanapp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.loanapplication'),
        ),
        migrations.AlterField(
            model_name='loanclosure',
            name='remaining_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='loanoffer',
            name='application_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.loanapplication'),
        ),
        migrations.AlterField(
            model_name='loanoffer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.company'),
        ),
        migrations.AlterField(
            model_name='loanoffer',
            name='interest_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='loanoffer',
            name='loanamount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='loanoffer',
            name='monthly_instalment',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='loanoffer',
            name='tenure',
            field=models.IntegerField(help_text='Duration of the loan in months'),
        ),
        migrations.AlterField(
            model_name='loantype',
            name='interest_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='loantype',
            name='max_loan_amt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='loantype',
            name='min_loan_amt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='payments',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='payments',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.company'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='loanapp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.loanapplication'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='penalties',
            name='panalty_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='penalties',
            name='penalty_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='penalties',
            name='penalty_reason',
            field=models.CharField(choices=[('Late Payment', 'Late Payment'), ('Missed Payment', 'Missed Payment')], max_length=50),
        ),
        migrations.AlterField(
            model_name='repaymentschedule',
            name='instalment_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='repaymentschedule',
            name='interest_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='repaymentschedule',
            name='principal_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='repaymentschedule',
            name='remaining_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='repaymentschedule',
            name='repayment_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='supporttickets',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.company'),
        ),
        migrations.AlterField(
            model_name='supporttickets',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer'),
        ),
    ]
