# Generated by Django 4.2.7 on 2024-09-26 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_collaterals_valuation_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdocuments',
            name='customer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_customers', to='mainapp.customer'),
            preserve_default=False,
        ),
    ]
