# Generated by Django 4.2.7 on 2024-10-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_customer_identification_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='checked_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='eligible_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='interest_basics',
            field=models.CharField(choices=[('365', '365 Days Basis'), ('other', 'Other Basis')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='is_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_calculation_method',
            field=models.CharField(choices=[('reducing_balance', 'Reducing Balance Method'), ('flat_rate', 'Flat Rate Method'), ('constant_repayment', 'Constant Repayment (Amortization)'), ('simple_interest', 'Simple Interest'), ('compound_interest', 'Compound Interest'), ('graduated_repayment', 'Graduated Repayment'), ('balloon_payment', 'Balloon Payment'), ('bullet_repayment', 'Bullet Repayment'), ('interest_first', 'Interest-Only Loans')], default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='repayment_mode',
            field=models.CharField(choices=[('principal_only', 'Principal Only'), ('interest_only', 'Interest Only'), ('both', 'Principal and Interest'), ('interest_first', 'Interest First, Principal Later'), ('principal_end', 'Principal at End, Interest Periodically')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='repayment_schedule',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('halfyearly', 'Half Yearly'), ('annually', 'Annually'), ('one_time', 'One Time')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='risk_factor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='risk_score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='tenure_type',
            field=models.CharField(choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
