# Generated by Django 4.2.7 on 2024-09-29 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_loan_workflow_stats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='interest_basics',
            field=models.CharField(choices=[('365', '365 Days Basis'), ('other', 'Other Basis')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_calculation_method',
            field=models.CharField(choices=[('reducing_balance', 'Reducing Balance Method'), ('flat_rate', 'Flat Rate Method'), ('constant_repayment', 'Constant Repayment (Amortization)'), ('simple_interest', 'Simple Interest'), ('compound_interest', 'Compound Interest'), ('graduated_repayment', 'Graduated Repayment'), ('balloon_payment', 'Balloon Payment'), ('bullet_repayment', 'Bullet Repayment'), ('interest_first', 'Interest-Only Loans')], default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='repayment_mode',
            field=models.CharField(choices=[('principal_only', 'Principal Only'), ('interest_only', 'Interest Only'), ('both', 'Principal and Interest'), ('interest_first', 'Interest First, Principal Later'), ('principal_end', 'Principal at End, Interest Periodically')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='repayment_schedule',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('halfyearly', 'Half Yearly'), ('annually', 'Annually'), ('one_time', 'One Time')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='repayment_start_date',
            field=models.DateField(blank=True,null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.bankaccount'),
        ),
    ]
