# Generated by Django 4.2.7 on 2024-09-29 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_loanapplication_interest_basics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repaymentschedule',
            name='loan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_loan', to='mainapp.loan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repaymentschedule',
            name='paid_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='repaymentschedule',
            name='period',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repaymentschedule',
            name='schedule_id',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='repayment_start_date',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repaymentschedule',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_payment_method', to='mainapp.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='repaymentschedule',
            name='repayment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='repaymentschedule',
            name='repayment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
    ]
