# Generated by Django 4.2.7 on 2024-09-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_repaymentschedule_loan_repaymentschedule_paid_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaterals',
            name='collateral_value',
            field=models.FloatField(default=0.0, help_text='Monetary value of the collateral'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='loancalculators',
            name='interest_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='loancalculators',
            name='loan_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
