# Generated by Django 4.2.7 on 2024-09-30 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_collaterals_collateral_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repaymentschedule',
            name='loan',
        ),
    ]
