# Generated by Django 4.2.7 on 2024-09-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_remove_repaymentschedule_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='paid_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
