# Generated by Django 4.2.7 on 2024-09-30 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_loan_paid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='loanapp_id',
        ),
        migrations.AddField(
            model_name='payments',
            name='loan_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.loan'),
            preserve_default=False,
        ),
    ]
