# Generated by Django 4.2.7 on 2024-09-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_remove_payments_loanapp_id_payments_loan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='disbursement_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
